### ISSUE TITLE
Create Simple Python Script

### ISSUE THREAD

**Issue by ijemmao** [ijemmao/webscraper#1]
## Background
To get the most out of the data that's being collected within this project, we want to create a word frequency (and maybe other types of) Python script that parses through provided data and identifies interesting trends. This ticket is focused on creating a basic Python script that will evolve into the word frequency script.

## Ideal Solution
For this ticket, create a basic Python script named `script.py` that lives at the top level of this repo that does the following:
1. Prints 'Running Word Frequency Script...' at the beginning of the script
2. Imports all JSON files from `articles/` and prints out all articles

## Main Goal
The main focus for this ticket is to get comfortable with importing files and modules in Python. You don't need to do anything beyond importing for this ticket, future tickets will increase in difficulty and complexity.

**Comment by izudada** [comment]
Hello, I am interested in this ticket. 

For the second requirement:
"Imports all JSON files from articles/ and prints out all articles".; what is the expected output to be printed out, the JSON filename or file content?
And if it is the file content, is the expectation to print the file content for the day?

**Comment by ijemmao** [comment]
@izudada Glad to hear that you're interested! The expected output for this issue is to generate a histogram of all words used in the articles. You don't need to render a real histogram, you could create an Object where the keys are the words and the values is the word frequency. That way we can use that object to retroactively update the `frequency` field on the [Igbo API Word documents](https://github.com/ijemmao/igbo_api/blob/master/src/models/Word.js#L33). (This is the most ideal use case)
